"""user_id to ping

Revision ID: d1d75028015f
Revises: 60c93d5dfbd0
Create Date: 2024-01-31 23:37:24.330648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d75028015f'
down_revision: Union[str, None] = '60c93d5dfbd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pings', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'pings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pings', type_='foreignkey')
    op.drop_column('pings', 'user_id')
    # ### end Alembic commands ###
