"""add count column

Revision ID: e6285ec0d9d2
Revises: 274cbd265765
Create Date: 2024-02-01 23:29:36.500455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6285ec0d9d2'
down_revision: Union[str, None] = '274cbd265765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pings', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
